FROM postgres:18

RUN chmod g-s /usr/local/bin/gosu && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        postgresql-17-postgis-3 \
        postgresql-17-postgis-3-scripts && \
    rm -rf /var/lib/apt/lists/*